{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: api-forge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.data.size | default "20Gi" }}
  {{- if .Values.postgres.persistence.data.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.data.storageClass }}
  {{- end }}
{{- end }}
