{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: api-forge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.data.size | default "10Gi" }}
  {{- if .Values.redis.persistence.data.storageClass }}
  storageClassName: {{ .Values.redis.persistence.data.storageClass }}
  {{- end }}
{{- end }}
