apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: api-forge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.persistence.logs.size | default "5Gi" }}
  {{- if .Values.app.persistence.logs.storageClass }}
  storageClassName: {{ .Values.app.persistence.logs.storageClass }}
  {{- end }}
