{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database-backup
    app.kubernetes.io/part-of: api-forge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.backups.size | default "50Gi" }}
  {{- if .Values.postgres.persistence.backups.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.backups.storageClass }}
  {{- end }}
{{- end }}
