{{- if and .Values.temporal.enabled .Values.temporal.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: temporal-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: temporal
  policyTypes:
    - Ingress
  ingress:
    {{- toYaml .Values.temporal.networkPolicy.ingress | nindent 4 }}
{{- end }}
