{{- if .Values.postgres }}
{{- if .Values.postgres.enabled }}
{{- if not .Values.postgres.ca.existingSecret }}
{{- fail "postgresql.ca.existingSecret must be provided" }}
{{- end }}
{{- end }}
{{- end }}
