{{- if .Values.postgres }}
{{- if .Values.postgres.enabled }}
{{- if not .Values.postgres.secrets.existingSecret }}
{{- fail "postgresql.secrets.existingSecret must be set when PostgreSQL is enabled" }}
{{- end }}
{{- end }}
{{- end }}
